### ISSUE TITLE
Tracking issue for stage 1 improvements

### ISSUE THREAD

**Issue by inakleinbottle** [terrylyons/libalgebra#8]
Tracking issue for stage 1 of #3.

- [x] Create a new interface class template for vectors. All higher classes will derive publicly from this interface class instead of the underlying vector class, and this will create a strict separation of data model form mathematical structure. The interface will derive privately from vector implementation and perform the correct dispatching for degree optimisation and similar features.
- [x] Implement a temporary `multiplication_operator` type that implements multiplication between key-value pairs based on the basis `prod` function, as it is currently implemented.
- [x] Move the implementation of the multiplication functionality from the `algebra` class into the `sparse_vector` class, since this is currently designed around the use of the `sparse_vector` type. This means implementing the `triangularbufferedmulitplyandcombine` and `squarebufferedmultiplyandcombine` functions from the algebra class in the `sparse_vector` class, and relevant interface methods in the `vector` interface. Since these no longer necessarily relate to multiplication, they should be renamed.
- [x] Shift the multiplication implementation from the `algebra` class versions to those provided on the `vector` interface class.
